// ─────────────────────────────────────────────────────────────
// ACADEMY COURSE CATALOG
// Add new courses here. Nothing else needs to change to add a
// course to the catalog page — just add an entry to this array.
// ─────────────────────────────────────────────────────────────

export interface AcademyCourse {
  slug: string;                 // URL: /academy/[slug]
  title: string;
  city: string;                 // "Elizabethtown", "Louisville", "Lexington", "Bowling Green"
  tagline: string;              // one-line sales hook
  description: string;          // longer sales-page description
  price: number;                // in USD, e.g. 49 for $49. 0 = free
  originalPrice?: number;       // for showing a "was $X" discount
  tag: string;                  // badge shown on catalog card, e.g. "Military"
  level: "Beginner" | "Intermediate" | "Advanced" | "All Levels";
  modules: number;
  lessons: number;
  estimatedHours: number;
  stripePaymentLink: string;    // Stripe Payment Link URL — set after creating the product in Stripe
  legacyFreeHref?: string;      // if this course also exists as a free page on the main site
  outcomes: string[];           // "what you'll learn" bullet list
  featured?: boolean;           // show prominently on catalog page
}

export const academyCourses: AcademyCourse[] = [
  {
    slug: "kentucky-home-buyers",
    title: "The Kentucky Home Buyers Course",
    city: "Elizabethtown",
    tagline: "Everything you need to buy a home in Kentucky, from credit score to keys.",
    description: "Six modules, thirty lessons, written specifically for buyers in Elizabethtown and Hardin County. Covers KHC down payment assistance, every Kentucky loan type, Kentucky attorney closings, and real local market data.",
    price: 0,
    tag: "Buyers",
    level: "Beginner",
    modules: 6,
    lessons: 30,
    estimatedHours: 3,
    stripePaymentLink: "",
    legacyFreeHref: "/course",
    outcomes: [
      "Know exactly how much you need to buy in Kentucky",
      "Understand FHA, VA, USDA, Conventional, and KHC loan programs",
      "Navigate Kentucky attorney closings with confidence",
      "Avoid the mistakes that cost buyers thousands",
    ],
    featured: true,
  },
  {
    slug: "kentucky-home-sellers",
    title: "The Kentucky Home Sellers Course",
    city: "Elizabethtown",
    tagline: "Price it right, prepare it well, and sell for more.",
    description: "A complete guide to selling your home in Hardin County — pricing strategy, preparation, disclosures, negotiating offers, and closing day.",
    price: 0,
    tag: "Sellers",
    level: "Beginner",
    modules: 6,
    lessons: 28,
    estimatedHours: 3,
    stripePaymentLink: "",
    legacyFreeHref: "/sellers-course",
    outcomes: [
      "Price your home using real comparable sales, not guesswork",
      "Know which repairs are worth the money before listing",
      "Understand Kentucky seller disclosure requirements",
      "Handle multiple offers like a pro",
    ],
  },
  {
    slug: "fort-knox-pcs-bootcamp",
    title: "Fort Knox PCS Bootcamp",
    city: "Elizabethtown",
    tagline: "The military home-buying guide built specifically for Fort Knox.",
    description: "Everything a Fort Knox family needs — VA loans, BAH strategy, on-post vs off-post math, and buying a home remotely before you arrive.",
    price: 0,
    tag: "Military",
    level: "Beginner",
    modules: 6,
    lessons: 26,
    estimatedHours: 2.5,
    stripePaymentLink: "",
    legacyFreeHref: "/fort-knox-course",
    outcomes: [
      "Understand exactly how your BAH translates to buying power",
      "Know the real financial difference between on-post and off-post",
      "Buy a home remotely before your report date if needed",
      "Use your VA loan benefit correctly, including the funding fee exemption",
    ],
  },
  {
    slug: "first-time-buyer-bootcamp",
    title: "First-Time Homebuyer Bootcamp",
    city: "Elizabethtown",
    tagline: "Never bought a home before? Start here.",
    description: "A ground-up guide for first-time buyers — credit, KHC assistance, the entire process explained in plain English with no assumptions.",
    price: 0,
    tag: "First-Time Buyers",
    level: "Beginner",
    modules: 6,
    lessons: 24,
    estimatedHours: 2.5,
    stripePaymentLink: "",
    legacyFreeHref: "/first-time-bootcamp",
    outcomes: [
      "Understand your credit score and how to improve it fast",
      "Learn what KHC down payment assistance can cover",
      "Walk through the entire process before you start looking",
      "Know what never to do between pre-approval and closing",
    ],
  },
  {
    slug: "kentucky-investor-course",
    title: "The Kentucky Real Estate Investor Course",
    city: "Elizabethtown",
    tagline: "Build a rental portfolio in Hardin County, the right way.",
    description: "Cash flow analysis, financing strategy, and how military rotation at Fort Knox creates a uniquely stable rental market.",
    price: 0,
    tag: "Investors",
    level: "Intermediate",
    modules: 6,
    lessons: 22,
    estimatedHours: 2.5,
    stripePaymentLink: "",
    legacyFreeHref: "/investor-course",
    outcomes: [
      "Run real cash flow numbers on a Hardin County rental",
      "Understand DSCR loans and multi-unit VA financing",
      "Build a strategy around Fort Knox rental demand",
      "Know what a good cap rate looks like locally",
    ],
  },

  {
    slug: "louisville-relocation-guide",
    title: "Moving to Louisville, KY: The Complete Buyer's Guide",
    city: "Louisville",
    tagline: "Cross-shopping Louisville and Elizabethtown? Know both markets before you decide.",
    description: "A market-overview course for buyers comparing Louisville to smaller Hardin County communities — commute reality, neighborhood price tiers, and how far your money goes in each direction on I-65.",
    price: 39,
    tag: "Relocation",
    level: "Beginner",
    modules: 4,
    lessons: 16,
    estimatedHours: 1.5,
    stripePaymentLink: "",
    outcomes: [
      "Compare Louisville neighborhood price tiers against Hardin County alternatives",
      "Understand the real commute tradeoffs along the I-65 corridor",
      "Know which Louisville suburbs offer the best value for families",
      "Avoid overpaying by understanding what drives Louisville pricing",
    ],
  },
  {
    slug: "lexington-relocation-guide",
    title: "Moving to Lexington, KY: The Complete Buyer's Guide",
    city: "Lexington",
    tagline: "A hometown perspective on buying in the Bluegrass.",
    description: "Built from firsthand knowledge of growing up in Lexington — horse country charm, UK-driven rental demand, and how Lexington's market compares to smaller Kentucky cities for buyers weighing their options.",
    price: 39,
    tag: "Relocation",
    level: "Beginner",
    modules: 4,
    lessons: 16,
    estimatedHours: 1.5,
    stripePaymentLink: "",
    outcomes: [
      "Understand Lexington's neighborhood character from someone who grew up there",
      "Know how University of Kentucky drives rental and resale demand",
      "Compare Lexington's cost of living against other Kentucky cities",
      "Identify up-and-coming Lexington-area neighborhoods worth watching",
    ],
  },
  {
    slug: "bowling-green-relocation-guide",
    title: "Moving to Bowling Green, KY: The Complete Buyer's Guide",
    city: "Bowling Green",
    tagline: "Kentucky's fastest-growing small city, explained for buyers.",
    description: "A market overview for buyers considering Bowling Green — WKU's impact on the rental market, the Corvette plant's economic influence, and how it compares to Elizabethtown for families and investors alike.",
    price: 39,
    tag: "Relocation",
    level: "Beginner",
    modules: 4,
    lessons: 16,
    estimatedHours: 1.5,
    stripePaymentLink: "",
    outcomes: [
      "Understand what's driving Bowling Green's rapid growth",
      "Know how WKU affects the local rental and resale market",
      "Compare Bowling Green and Elizabethtown side by side",
      "Identify the best neighborhoods for families versus investors",
    ],
  },

  {
    slug: "credit-repair-before-you-buy",
    title: "Credit Repair Before You Buy",
    city: "Elizabethtown",
    tagline: "A complete, step-by-step system for raising your credit score before you apply for a mortgage.",
    description: "Nine in-depth lessons covering exactly how your score is calculated, how to dispute real errors, the fastest legitimate ways to improve utilization, how to handle collections and charge-offs, and a full 90-day action plan sequenced for maximum impact before you apply for a home loan.",
    price: 39,
    tag: "Money & Mindset",
    level: "Beginner",
    modules: 1,
    lessons: 9,
    estimatedHours: 2.5,
    stripePaymentLink: "",
    outcomes: [
      "Understand exactly which five factors control your credit score and how much each one matters",
      "Know how to dispute genuine errors correctly and what to expect from the process",
      "Master the fastest legitimate lever available: credit utilization strategy",
      "Handle collections, charge-offs, and old debt with a clear, informed strategy",
      "Follow a complete 90-day action plan sequenced specifically for a mortgage timeline",
    ],
    featured: true,
  },
  {
    slug: "how-much-house-can-you-afford",
    title: "How Much House Can You Actually Afford",
    city: "Elizabethtown",
    tagline: "Build your real number — not the bank's number — before you start looking at homes.",
    description: "Eight in-depth lessons walking you through the true cost of homeownership: the difference between what a lender approves and what you can actually afford, gross vs. net income, full PITI, hidden ownership costs, debt-to-income ratio, down payment tradeoffs, and a complete step-by-step worksheet to calculate your real, honest budget.",
    price: 39,
    tag: "Money & Mindset",
    level: "Beginner",
    modules: 1,
    lessons: 8,
    estimatedHours: 2,
    stripePaymentLink: "",
    outcomes: [
      "Understand why a lender's pre-approval number is not the number you should spend",
      "Calculate your real budget using net income, not gross income",
      "Know the true full cost of a mortgage payment, including taxes, insurance, and PMI",
      "Budget for the hidden costs of homeownership most new buyers miss entirely",
      "Build a complete, personalized affordability worksheet you can actually use",
    ],
    featured: true,
  },
  {
    slug: "buying-with-bad-credit-or-thin-credit",
    title: "Buying With Bad Credit or Thin Credit",
    city: "Elizabethtown",
    tagline: "Real paths to a mortgage, whether you have credit damage or barely any credit history at all.",
    description: "Eight in-depth lessons distinguishing bad credit from thin credit, the loan programs and compensating factors that can offset a lower score, the fastest legitimate ways to build a thin file, how manual underwriting actually works, co-signer considerations, Kentucky-specific assistance programs, and a complete action plan based on your specific situation.",
    price: 39,
    tag: "Buyers",
    level: "Beginner",
    modules: 1,
    lessons: 8,
    estimatedHours: 2,
    stripePaymentLink: "",
    outcomes: [
      "Know whether your situation is bad credit, thin credit, or both — and why the strategy differs",
      "Understand which loan programs and compensating factors work in your favor",
      "Build a thin credit file quickly using proven, low-risk strategies",
      "Understand exactly what manual underwriting involves and how to find a lender who does it well",
      "Know which Kentucky-specific programs exist to support credit-challenged buyers",
    ],
    featured: true,
  },

  {
    slug: "every-kentucky-loan-program-explained",
    title: "Every Kentucky Loan Program Explained",
    city: "Elizabethtown",
    tagline: "Conventional, FHA, VA, USDA, and KHC assistance — compared side by side so you know exactly which one fits you.",
    description: "Seven in-depth lessons covering how to think about loan programs, a full breakdown of conventional, FHA, VA, and USDA loans, Kentucky Housing Corporation down payment assistance explained in detail, and a complete side-by-side comparison framework to identify which program actually fits your specific credit, income, and eligibility.",
    price: 39,
    tag: "Buyers",
    level: "Beginner",
    modules: 1,
    lessons: 7,
    estimatedHours: 2,
    stripePaymentLink: "",
    outcomes: [
      "Understand the four questions that actually differentiate one loan program from another",
      "Know the real tradeoffs between conventional and FHA financing, including long-term PMI costs",
      "Understand VA's unique advantages for eligible military buyers",
      "Know whether USDA's zero-down option applies to your target property",
      "Understand how KHC down payment assistance can pair with any of these programs",
    ],
    featured: true,
  },
  {
    slug: "bidding-war-without-overpaying",
    title: "How to Win a Bidding War Without Overpaying",
    city: "Elizabethtown",
    tagline: "Compete effectively in a multiple-offer situation without losing your financial discipline.",
    description: "Five in-depth lessons covering what actually creates competitive situations, the real pre-approval strength sellers look for, smart price strategy that protects your budget, the non-price terms that often win over the highest bidder, and a complete competitive offer checklist you can use every time.",
    price: 39,
    tag: "Buyers",
    level: "Intermediate",
    modules: 1,
    lessons: 5,
    estimatedHours: 1.5,
    stripePaymentLink: "",
    outcomes: [
      "Understand what conditions actually create a bidding war in the first place",
      "Know what real financing strength looks like from a seller's perspective",
      "Set a real price ceiling and stick to it under competitive pressure",
      "Use non-price terms strategically to win without simply paying more",
    ],
  },
  {
    slug: "home-inspection-deep-dive",
    title: "The Home Inspection Deep Dive",
    city: "Elizabethtown",
    tagline: "Know exactly what an inspection covers, what it doesn't, and how to prioritize what actually matters.",
    description: "Five in-depth lessons covering what a home inspection actually is and isn't, how to choose the right inspector, what to look for in roof and structural findings, electrical/plumbing/HVAC considerations, and how to read a full report and prioritize real issues over routine maintenance notes.",
    price: 39,
    tag: "Buyers",
    level: "Beginner",
    modules: 1,
    lessons: 5,
    estimatedHours: 1.5,
    stripePaymentLink: "",
    outcomes: [
      "Understand the real scope and limits of a standard home inspection",
      "Know how to choose an inspector who will actually be thorough",
      "Recognize the difference between minor settling and serious structural concern",
      "Prioritize safety and major system findings over routine maintenance items",
    ],
  },
  {
    slug: "appraisal-gaps-how-to-handle-them",
    title: "Appraisal Gaps and How to Handle Them",
    city: "Elizabethtown",
    tagline: "What actually happens when a home appraises below your offer price, and every realistic path forward.",
    description: "Five in-depth lessons covering exactly what an appraisal gap is, how the appraisal contingency protects you, every realistic option when a gap occurs, how to formally request a reconsideration of value, and how to reduce your risk of facing a gap in the first place.",
    price: 39,
    tag: "Buyers",
    level: "Intermediate",
    modules: 1,
    lessons: 5,
    estimatedHours: 1.5,
    stripePaymentLink: "",
    outcomes: [
      "Understand exactly why an appraisal gap creates a financing problem",
      "Know what waiving an appraisal contingency actually commits you to",
      "Understand all five realistic paths forward when a gap occurs",
      "Know how to formally challenge an appraisal that contains real errors",
    ],
  },
  {
    slug: "buying-a-fixer-upper",
    title: "Buying a Fixer-Upper",
    city: "Elizabethtown",
    tagline: "An honest, complete guide to whether a renovation project is actually the right decision for you.",
    description: "Five in-depth lessons covering an honest self-assessment before you look, the critical difference between cosmetic and structural issues, how to get renovation estimates you can trust, real financing options for renovation projects, and a complete final decision framework for any specific property.",
    price: 39,
    tag: "Buyers",
    level: "Intermediate",
    modules: 1,
    lessons: 5,
    estimatedHours: 1.5,
    stripePaymentLink: "",
    outcomes: [
      "Honestly assess your own financial and emotional readiness for a renovation project",
      "Distinguish between lower-risk cosmetic work and higher-risk structural issues",
      "Get renovation estimates you can actually rely on, with a proper contingency built in",
      "Understand FHA 203(k), HomeStyle, and VA renovation financing options",
    ],
  },

  {
    slug: "buying-new-construction-in-kentucky",
    title: "Buying New Construction in Kentucky",
    city: "Elizabethtown",
    tagline: "How buying from a builder is genuinely different, and how to protect yourself through the process.",
    description: "Five in-depth lessons covering how new construction differs from resale, understanding the builder's contract, navigating the design center without overspending, why you still need independent inspections, and financing considerations specific to longer construction timelines.",
    price: 39,
    tag: "Buyers",
    level: "Intermediate",
    modules: 1,
    lessons: 5,
    estimatedHours: 1.5,
    stripePaymentLink: "",
    outcomes: [
      "Understand why you need your own agent registered before your first builder visit",
      "Know what to watch for in a builder's proprietary contract",
      "Navigate design center upgrades without letting the budget balloon",
      "Understand why independent inspections still matter for a brand-new home",
    ],
  },
  {
    slug: "buying-with-a-cosigner-or-joint-buyer",
    title: "Buying With a Co-Signer or Joint Buyer",
    city: "Elizabethtown",
    tagline: "Understand exactly what you're agreeing to before bringing someone else onto your mortgage.",
    description: "Five in-depth lessons covering the real differences between a co-borrower, co-signer, and joint buyer, how lenders actually combine two financial profiles, the genuine risk for anyone agreeing to co-sign, how title ownership structures work, and planning a clear exit strategy from the start.",
    price: 39,
    tag: "Buyers",
    level: "Intermediate",
    modules: 1,
    lessons: 5,
    estimatedHours: 1.5,
    stripePaymentLink: "",
    outcomes: [
      "Know the real legal difference between a co-borrower, co-signer, and joint buyer",
      "Understand how a lender actually combines two people's credit and income",
      "Recognize the genuine long-term risk involved in co-signing for someone else",
      "Plan a clear exit strategy and title structure before you ever need one",
    ],
  },
  {
    slug: "the-kentucky-attorney-closing-explained",
    title: "The Kentucky Attorney Closing, Explained",
    city: "Elizabethtown",
    tagline: "A complete walkthrough of Kentucky's required attorney closing process, from title examination to your first weeks as a homeowner.",
    description: "Five in-depth lessons covering why Kentucky requires an attorney at closing, what a title examination actually investigates, how to properly review your Closing Disclosure, exactly what happens at the closing table, and what to do in the days and weeks after you close.",
    price: 39,
    tag: "Buyers",
    level: "Beginner",
    modules: 1,
    lessons: 5,
    estimatedHours: 1.5,
    stripePaymentLink: "",
    outcomes: [
      "Understand why Kentucky requires attorney involvement in every residential closing",
      "Know what a title examination is actually checking for on your behalf",
      "Review your Closing Disclosure correctly during your legal three-day window",
      "Know exactly what to expect, step by step, at your actual closing appointment",
    ],
  },
  {
    slug: "pricing-your-home-to-sell-fast-and-high",
    title: "Pricing Your Home to Sell Fast and High",
    city: "Elizabethtown",
    tagline: "Why the first two weeks matter more than anything else, and how to price correctly from day one.",
    description: "Five in-depth lessons covering why initial pricing determines almost everything that follows, how to properly read and adjust comparable sales, choosing the right pricing strategy for your situation, the psychology of specific price points, and knowing when and how to adjust if your price isn't working.",
    price: 39,
    tag: "Sellers",
    level: "Beginner",
    modules: 1,
    lessons: 5,
    estimatedHours: 1.5,
    stripePaymentLink: "",
    outcomes: [
      "Understand why the first two weeks of a listing matter more than any point afterward",
      "Read and properly adjust comparable sales like a professional, not just an average",
      "Choose the pricing strategy that actually fits your timeline and market conditions",
      "Know when and how to make a meaningful price adjustment if needed",
    ],
    featured: true,
  },
  {
    slug: "prepping-your-home-on-a-budget",
    title: "Prepping Your Home on a Budget",
    city: "Elizabethtown",
    tagline: "The real ROI hierarchy for pre-listing improvements, and what to skip entirely.",
    description: "Five in-depth lessons covering the real ROI hierarchy of home improvements, decluttering and depersonalizing effectively, curb appeal improvements under $500, a strategic approach to paint, and small repairs with outsized impact on buyer perception.",
    price: 39,
    tag: "Sellers",
    level: "Beginner",
    modules: 1,
    lessons: 5,
    estimatedHours: 1.5,
    stripePaymentLink: "",
    outcomes: [
      "Know which pre-listing improvements actually return their cost and which don't",
      "Declutter and depersonalize effectively using a proven professional target",
      "Improve curb appeal meaningfully for under $500",
      "Prioritize paint and small repairs strategically on a limited budget",
    ],
  },

  {
    slug: "selling-an-inherited-home",
    title: "Selling an Inherited Home",
    city: "Elizabethtown",
    tagline: "A practical and compassionate guide through probate, sorting belongings, taxes, and the sale itself.",
    description: "Five in-depth lessons covering the emotional and practical starting point, understanding probate and how it affects your timeline, sorting a lifetime of belongings, tax considerations specific to inherited property including the stepped-up basis, and deciding between selling as-is or preparing the home.",
    price: 39,
    tag: "Sellers",
    level: "Beginner",
    modules: 1,
    lessons: 5,
    estimatedHours: 1.5,
    stripePaymentLink: "",
    outcomes: [
      "Understand the emotional and legal dimensions of this process happening simultaneously",
      "Know how probate works and how it affects your ability to sell",
      "Have a practical system for sorting a lifetime of belongings",
      "Understand the stepped-up basis and other tax considerations unique to inherited property",
    ],
  },
  {
    slug: "selling-during-a-divorce",
    title: "Selling During a Divorce",
    city: "Elizabethtown",
    tagline: "Navigating the sale of a shared home with clear communication, proper legal coordination, and appropriate patience.",
    description: "Five in-depth lessons covering the first decisions that shape everything else, working together through a difficult process, dividing proceeds and financial considerations, the practical and emotional realities unique to this situation, and a complete step-by-step process checklist.",
    price: 39,
    tag: "Sellers",
    level: "Intermediate",
    modules: 1,
    lessons: 5,
    estimatedHours: 1.5,
    stripePaymentLink: "",
    outcomes: [
      "Understand the foundational legal decisions that need to happen before listing",
      "Establish clear communication processes for navigating the sale together",
      "Know how proceeds are typically divided and the tax timing considerations involved",
      "Choose an agent and process that accounts for this situation's unique demands",
    ],
  },
  {
    slug: "downsizing-a-sellers-guide",
    title: "Downsizing: A Seller's Guide",
    city: "Elizabethtown",
    tagline: "Deciding if and when to downsize, and navigating the emotional and financial transition well.",
    description: "Five in-depth lessons covering whether and when downsizing actually makes sense, the emotional work of letting go of a long-held home, financial planning specific to this transition, evaluating downsized housing options, and preparing and selling your current home.",
    price: 39,
    tag: "Sellers",
    level: "Beginner",
    modules: 1,
    lessons: 5,
    estimatedHours: 1.5,
    stripePaymentLink: "",
    outcomes: [
      "Evaluate honestly whether and when downsizing fits your situation",
      "Navigate the emotional work of leaving a long-held home with appropriate support",
      "Understand the real financial planning considerations, including buy-first vs sell-first",
      "Evaluate the full range of downsized housing options beyond just a smaller single-family home",
    ],
  },
  {
    slug: "for-sale-by-owner-what-youre-signing-up-for",
    title: "For Sale By Owner: What You're Signing Up For",
    city: "Elizabethtown",
    tagline: "An honest look at what FSBO actually involves, before you commit to selling without representation.",
    description: "Five in-depth lessons covering the honest case for and against FSBO, pricing without professional MLS access, marketing without agent networks, your full legal and disclosure obligations, and what it's actually like negotiating directly against a professional buyer's agent.",
    price: 39,
    tag: "Sellers",
    level: "Intermediate",
    modules: 1,
    lessons: 5,
    estimatedHours: 1.5,
    stripePaymentLink: "",
    outcomes: [
      "Understand the genuine tradeoffs of FSBO, including what the data shows about typical outcomes",
      "Know how to price your home without full professional MLS access",
      "Understand your complete legal and disclosure obligations as an FSBO seller",
      "Recognize what you're up against negotiating directly with a buyer's professional agent",
    ],
  },

  {
    slug: "handling-multiple-offers-like-a-pro",
    title: "Handling Multiple Offers Like a Pro",
    city: "Elizabethtown",
    tagline: "A complete, three-module system for evaluating and winning the best outcome from competing offers.",
    description: "Three in-depth modules covering understanding the situation you're in, your three strategic response options (accept, counter, or call for highest and best), and how to evaluate offers holistically beyond price alone — financing strength, contingencies, timeline, and making your final decision with real confidence.",
    price: 39,
    tag: "Sellers",
    level: "Intermediate",
    modules: 3,
    lessons: 6,
    estimatedHours: 2,
    stripePaymentLink: "",
    outcomes: [
      "Understand your actual legal disclosure obligations regarding competing offers",
      "Know the real tradeoffs between accepting, countering, or calling for highest and best",
      "Evaluate financing strength, contingencies, and timeline alongside price",
      "Build a complete, confident decision framework for any multiple-offer situation",
    ],
    featured: true,
  },
  {
    slug: "negotiating-repairs-after-inspection",
    title: "Negotiating Repairs After Inspection",
    city: "Elizabethtown",
    tagline: "A complete, three-module system for responding to repair requests without overpaying or losing the deal.",
    description: "Three in-depth modules covering the post-inspection landscape and your disclosure history, evaluating what's actually worth negotiating with real contractor estimates, and structuring your response — choosing between repairs, credits, or price reduction, and knowing when to hold firm versus compromise.",
    price: 39,
    tag: "Sellers",
    level: "Intermediate",
    modules: 3,
    lessons: 6,
    estimatedHours: 2,
    stripePaymentLink: "",
    outcomes: [
      "Understand the formal post-inspection process and your real response options",
      "Categorize requests by severity and get real contractor estimates before responding",
      "Choose intelligently between completing repairs, offering credits, or reducing price",
      "Know when to hold firm and when a reasonable compromise serves you better",
    ],
    featured: true,
  },
  {
    slug: "selling-while-you-still-owe-more-than-its-worth",
    title: "Selling While You Still Owe More Than It's Worth",
    city: "Elizabethtown",
    tagline: "A complete, three-module guide to navigating being underwater on your mortgage with real options and real numbers.",
    description: "Three in-depth modules covering understanding your actual situation and real shortfall calculation, your realistic options including bringing cash, short sales, and alternatives to selling now, and making your decision with the emotional weight and complete framework this situation deserves.",
    price: 39,
    tag: "Sellers",
    level: "Intermediate",
    modules: 3,
    lessons: 6,
    estimatedHours: 2,
    stripePaymentLink: "",
    outcomes: [
      "Calculate your real, complete financial shortfall including all selling costs",
      "Understand every realistic option: cash coverage, short sale, or waiting it out",
      "Know when a short sale genuinely makes sense versus other alternatives",
      "Build a complete decision framework and know which professionals to consult",
    ],
  },
  {
    slug: "staging-on-zero-budget",
    title: "Staging on Zero Budget",
    city: "Elizabethtown",
    tagline: "A complete, three-module system of staging techniques that cost nothing but your own time and effort.",
    description: "Three in-depth modules covering the free fundamentals every seller should do first, rearranging what you already own for maximum impact, and room-by-room zero-cost staging tactics for every space buyers scrutinize most closely.",
    price: 39,
    tag: "Sellers",
    level: "Beginner",
    modules: 3,
    lessons: 6,
    estimatedHours: 2,
    stripePaymentLink: "",
    outcomes: [
      "Apply the 30 percent declutter rule and a genuine deep clean standard",
      "Rearrange existing furniture and lighting for maximum spaciousness and light",
      "Stage your entry, living areas, kitchen, bathrooms, and bedrooms at zero cost",
      "Understand the psychological principles behind why these techniques actually work",
    ],
  },

  {
    slug: "va-loans-explained-front-to-back",
    title: "VA Loans Explained Front to Back",
    city: "Elizabethtown",
    tagline: "A complete, three-module deep dive into the most powerful mortgage benefit available to Fort Knox families.",
    description: "Three in-depth modules covering eligibility and fundamentals, the financial mechanics including the funding fee and entitlement reuse, and the loan process including VA appraisal requirements, assumability, and refinancing options.",
    price: 39,
    tag: "Military",
    level: "Beginner",
    modules: 3,
    lessons: 6,
    estimatedHours: 2,
    stripePaymentLink: "",
    outcomes: [
      "Know exactly who qualifies and how to obtain your Certificate of Eligibility",
      "Understand the funding fee, exemptions, and how entitlement can be reused",
      "Know VA's Minimum Property Requirements and how they affect your property search",
      "Understand VA loan assumability and refinancing options for long-term flexibility",
    ],
    featured: true,
  },
  {
    slug: "on-post-vs-off-post-the-real-math",
    title: "On-Post vs Off-Post: The Real Math",
    city: "Elizabethtown",
    tagline: "A complete, three-module financial comparison for Fort Knox families deciding where to live.",
    description: "Three in-depth modules covering how BAH actually works and the honest on-post experience, the real three-year equity comparison with complete cost accounting, and making the decision for your specific situation including the long-term portfolio perspective.",
    price: 39,
    tag: "Military",
    level: "Beginner",
    modules: 3,
    lessons: 6,
    estimatedHours: 2,
    stripePaymentLink: "",
    outcomes: [
      "Understand exactly how BAH works and the honest tradeoffs of on-post housing",
      "Run a real three-year equity comparison using your own actual numbers",
      "Account for the complete true cost of off-post ownership, not just the mortgage",
      "Build a complete decision framework weighing financial and non-financial factors together",
    ],
    featured: true,
  },
  {
    slug: "buying-a-home-remotely-before-you-arrive",
    title: "Buying a Home Remotely Before You Arrive",
    city: "Elizabethtown",
    tagline: "A complete, three-module guide to buying with confidence before your report date.",
    description: "Three in-depth modules covering setting up for success before you start looking, evaluating properties you can't physically visit including thorough video walkthroughs and inspections, and closing and moving in without being there.",
    price: 39,
    tag: "Military",
    level: "Intermediate",
    modules: 3,
    lessons: 6,
    estimatedHours: 2,
    stripePaymentLink: "",
    outcomes: [
      "Get pre-approved and prepared before your search even begins",
      "Know what a genuinely thorough video walkthrough should actually cover",
      "Understand why the inspection contingency matters even more for remote buyers",
      "Navigate Kentucky's remote closing process and wire fraud safety with confidence",
    ],
  },
  {
    slug: "selling-or-renting-when-you-pcs-out",
    title: "Selling or Renting When You PCS Out",
    city: "Elizabethtown",
    tagline: "A complete, three-module framework for deciding what to do with your home when orders arrive.",
    description: "Three in-depth modules covering the core decision framework and honest questions to ask first, the renting path in depth including real cash flow numbers and distance management, and making your final decision including the long-term portfolio perspective.",
    price: 39,
    tag: "Military",
    level: "Intermediate",
    modules: 3,
    lessons: 6,
    estimatedHours: 2,
    stripePaymentLink: "",
    outcomes: [
      "Ask the right foundational questions before deciding either way",
      "Calculate real rental cash flow numbers, not optimistic assumptions",
      "Understand your real options for managing a rental property from a distance",
      "Know how this decision could connect to a longer-term portfolio strategy if that fits your goals",
    ],
  },

  // ── FUTURE PAID COURSES GO HERE ──
  // Example template for a new paid course:
  // {
  //   slug: "your-new-course-slug",
  //   title: "Course Title",
  //   tagline: "One sentence hook",
  //   description: "Longer sales description...",
  //   price: 49,
  //   originalPrice: 79,
  //   tag: "Category",
  //   level: "Beginner",
  //   modules: 4,
  //   lessons: 20,
  //   estimatedHours: 2,
  //   stripePaymentLink: "https://buy.stripe.com/xxxxx",
  //   outcomes: ["...", "...", "...", "..."],
  // },
];

export function getCourseBySlug(slug: string): AcademyCourse | undefined {
  return academyCourses.find((c) => c.slug === slug);
}

export function getFreeCourses(): AcademyCourse[] {
  return academyCourses.filter((c) => c.price === 0);
}

export function getPaidCourses(): AcademyCourse[] {
  return academyCourses.filter((c) => c.price > 0);
}

export function getCoursesByCity(city: string): AcademyCourse[] {
  return academyCourses.filter((c) => c.city === city);
}

export function getAllCities(): string[] {
  return Array.from(new Set(academyCourses.map((c) => c.city)));
}
